language: node_js
node_js: node
cache:
  directories:
    - node_modules
# before_deploy: 
#       - npm install netlify-cli -g
#       - npm run build
# script:
#   - npm test
# env:
#   - CI=true
jobs:  
  include:
    - stage: "Tests"                
      name: "ESS Lint"            
      script: eslint src/components/**/**
    - script: sass-lint 'src/**/*.scss' -v -q  
      name: "SASS Lint"     
    - script: npm test   
      name: "Unit Test Execution"      
    - stage: Deploy
      name: "Install netlify"            
      script: npm install netlify-cli -g                 
    - script: npm run build
      name: "Build Application"      
    - script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
      name: "Deploy to Netlify"
#       skip_cleanup: true
#       on:
#         branch: master
