language: node_js
node_js: node
cache:
  directories:
    - node_modules
# script:
#   - npm test
# env:
#   - CI=true
jobs:  
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "ESS Lint"            # names the first Tests stage job
      script: eslint src/components/**
    - script: sass-lint 'src/**/*.scss' -v -q  
      name: "SASS Lint"     # names the second Tests stage job
    - script: npm test   
      name: "Unit Test Execution"
#     - stage: deploy
#       name: "Deploy to Netlify"      
#       provider: script
#       script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
#       skip_cleanup: true
#       on:
#         branch: master
# before_deploy: 
#       - npm install netlify-cli -g
#       - npm run build